### ISSUE TITLE
add improg package

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-pkg-ubuntu#114]
see also https://github.com/rsyslog/rsyslog/issues/4339#issuecomment-654606367  (in hidden part!)

**Comment by rgerhards** [comment]
@ebsf1 pls take note

**Comment by ebsf1** [comment]
@rgerhards  thanks.

I can see the code has been added here but it doesn't seem to have made its way to the OBS repositories.

```
~$ sudo apt install rsyslog-improg 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package rsyslog-improg
```

Is this available in the daily stable build, however?

**Comment by rgerhards** [comment]
I am currently working on this. As I ATM seem to be the only one who manages git, crafts patches and features, packages and builds CI, it takes some time to propagate into the production systems ;-) [e,g, right now I am working on packaging CI]. Will see if I can push it up to the official OBS repo soon.

And, no, it will not make it to the daily stable PPA builds ATM - requires some adaption there as well. I also need to investigate what is the issue with the pub key on 16.04, as this is managed by OBS.

**Comment by ebsf1** [comment]
@rgerhards , good, and thanks.  It may make sense to include both imkmsg and improg at the same time, while you're at it.  The 16.04 pub key issue is binary, of course.

Once I have access to a repository with both modules, I can test whether one or the other will get imuxsock to read local kernel messages.  If improg works according to its documentation, I may have a hack.  Otherwise, imkmsg is an unknown quantity but it is the last remaining option before declaring a bug in imuxsock.  An imfile hack also may exist but it seems fragile, or at least inelegant.  Perhaps @davidelang or others on the mailing list have made progress with the experimental configuration file I posted there and at https://github.com/rsyslog/rsyslog/issues/4344

So, please let me know when the OBS build (or any other, with both modules) is ready, if possible.

Until then, I'll try to get rsyslog installed again on 16.04, and see about the imfile hack.

**Comment by rgerhards** [comment]
just for a test, you can use https://build.opensuse.org/package/show/home:rainergerhards:branches:home:rgerhards/rsyslog -- but this may change at any instant (but not within the next ~15 hrs). It's my playground.

**Comment by ebsf1** [comment]
It turns out the pubkey issue is a simple matter of permissions.  The pubkey in /etc/apt/trusted.gpg.d was root:root/640 and should be 644.

**Comment by ebsf1** [comment]
@rgerhards , thanks.  I went to the link but downloading requires a username and password, so I couldn't access things.

Working on installing from the 16.04 OBS repository again, now that I have the pubkey issue figured out.  Will advise on imkmsg and improg progress.
