### ISSUE TITLE
daily packages do no longer build

### ISSUE THREAD

**Issue by rgerhards** [rsyslog/rsyslog-pkg-ubuntu#30]
since roughly the last release

**Comment by davidelang** [comment]
odds are this is related to the cleanup I did. The errors I've seen in e-mail aren't very descriptive.

What are the scripts that run to execute the daily builds? I can take a look at trying to duplicate the problem

**Comment by davidelang** [comment]
note that it is a normal thing for the PPA variable to not be defined. Only Adiscon generates PPAs normally. The intent of my patches that introduced this variable were that if the variable was defined it would try and upload the ppa, but if it wasn't, it would silently skip that step.

could you make it so that the PPA not being defined is only fatal when running on your systems?

Also, with the current version as of 4/20, auto_daily_project doesn't seem to be invoking config.sh so it's not picking up the variables defined there.

**Comment by rgerhards** [comment]
fixed some while ago, obviously this was forgotten to close.
