### ISSUE TITLE
Build librdkafka with SSL support

### ISSUE THREAD

**Issue by hrak** [rsyslog/rsyslog-pkg-ubuntu#63]
librdkafka (or 'adisconhelperlrdk') appears to be built without SSL support. Trying to configure omkafka with `security.protocol=SSL` will throw a 

```
error in kafka parameter 'security.protocol=SSL': Invalid value for configuration property "security.protocol" [v8.28.0 try http://www.rsyslog.com/e/1000 ]
```

adding libssl-dev to Build-Depends of the control file of adisconhelperlrdk should do the trick.

**Comment by friedl** [comment]
Dependency was added. Please confirm it is working now.

**Comment by hrak** [comment]
Did not test yet, but looks good (in my builds i was using `sed -i 's/libsasl2-dev/libsasl2-dev, libssl-dev/' debian/control` which is basically what you did :) )

Is there a reason why this was only done in `v8-stable/debian` sections and not in `master/debian`?

**Comment by friedl** [comment]
The reason is, that there is currently no Kafka support in the daily builds. The control files are already present, but currently not maintained. 

The problem here is, that we do not have a good hint at how to properly build the adisconhelperlrdk daily, just like our other dependencies, with daily pull of the git branch and making the tarball ourselves. Basically, we could do this, but we do not know of the specifics for the librdkafka release tarball, so we can build the same through the daily build script.

If you have any clues, that would be much appreciated.

**Comment by friedl** [comment]
@hrak In the meantime we could add the Kafka support in the daily builds. So you could try again with that.
